apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.26.0
    helm:
      values: |
        minecraftServer:
          eula: true
          difficulty: normal
          maxPlayers: 20
          whitelist: ""
          ops: ""
          gameMode: survival
          motd: "Kubernetes Minecraft Server"
          memory: 3G

        persistence:
          storageClass: "local-path"
          dataDir:
            enabled: true
            size: 5Gi
            storageClass: "local-path"

        service:
          type: LoadBalancer

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - talos-06

        terminationGracePeriodSeconds: 120

  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
