apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grafana/agent.git
    targetRevision: main
    path: production/operator/crds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
        - .metadata.labels
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
