apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: s3
            s3:
              endpoint: minio.monitoring.svc.cluster.local:9000
              bucketnames: loki-data
              access_key_id: minioadmin
              secret_access_key: minioadmin
              insecure: true
              s3forcepathstyle: true
          commonConfig:
            replication_factor: 2
          limitsConfig:
            retention_period: 30d

        # Now we can use SimpleScalable mode since we have object storage
        deploymentMode: SimpleScalable

        # Disable single binary mode
        singleBinary:
          replicas: 0

        # Enable and configure SimpleScalable mode
        simpleScalable:
          enabled: true
          # Read components (queriers)
          read:
            replicas: 2
          # Write components (distributors, ingesters)
          write:
            replicas: 2

        # Other configurations remain the same
        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false
        gateway:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
