apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: filesystem
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 2
          limitsConfig:
            retention_period: 30d

        deploymentMode: SimpleScalable

        singleBinary:
          replicas: 0

        simpleScalable:
          enabled: true

          read:
            replicas: 2
            persistence:
              enabled: true
              size: 10Gi
              storageClass: synology-loki

          write:
            replicas: 2
            persistence:
              enabled: true
              size: 30Gi
              storageClass: synology-loki

        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false
        gateway:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
