apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 2
          limitsConfig:
            retention_period: 30d
          storage:
            bucketNames:
              chunks: loki-data
              ruler: loki-ruler
              admin: loki-admin
            s3:
              s3: null  # Required default value
              endpoint: minio.monitoring.svc.cluster.local:9000
              region: us-east-1  # Required default value
              secretAccessKey: minioadmin
              accessKeyId: minioadmin
              signatureVersion: v4
              s3ForcePathStyle: true
              insecure: true

        deploymentMode: SimpleScalable

        singleBinary:
          replicas: 0

        simpleScalable:
          enabled: true
          read:
            replicas: 2
          write:
            replicas: 2

        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false
        gateway:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
