apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.48.0
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          persistence:
            enabled: true
            storageClass: synology-loki
            accessMode: ReadWriteOnce
            size: 10Gi
          config: |
            limits_config:
              retention_period: 360h
        singleBinary:
          replicas: 1
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
