apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.8.9
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: filesystem
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 1
            limits_config:
              retention_period: 30d
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 30Gi
            storageClass: synology-loki
            name: storage
            accessMode: ReadWriteOnce
        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false
        gateway:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
