apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.45.2
    helm:
      values: |
        loki:
          auth_enabled: false
          deploymentMode: SingleBinary
          storage:
            type: filesystem
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 1
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 30d
        singleBinary:
          readinessProbe:
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 15
          replicas: 1
          persistence:
            enabled: true
            size: 30Gi
            storageClass: synology-loki
            name: storage
            accessMode: ReadWriteOnce
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false
        gateway:
          enabled: false
        test:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    #automated:
      #prune: true
      #selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
