grafana:
  persistence:
    enabled: true
    storageClassName: synology-nfs
    size: 10Gi
    subPath: grafana
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: workload-type/monitoring
              operator: In
              values:
              - "true"
