apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      values: |
        # Force only 1 replica for all components
        global:
          replicas: 1

        loki:
          useTestSchema: true
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          limits_config:
            retention_period: 30d
            allow_structured_metadata: false
          storage:
            bucketNames:
              chunks: loki-data
              ruler: loki-ruler
              admin: loki-admin
            s3:
              s3: null
              endpoint: minio.monitoring.svc.cluster.local:9000
              region: us-east-1
              secretAccessKey: minioadmin
              accessKeyId: minioadmin
              signatureVersion: v4
              s3ForcePathStyle: true
              insecure: true

        extraArgs:
          all:
            - "-validation.allow-structured-metadata=false"

        gateway:
          enabled: true
          replicas: 1

        deploymentMode: SimpleScalable

        singleBinary:
          replicas: 0

        simpleScalable:
          enabled: true

          backend:
            replicas: 1
            # Force single instance
            affinity: null
            podAntiAffinity: null
            persistence:
              enabled: true
              size: 10Gi
              storageClass: synology-loki
              accessMode: ReadWriteOnce

          read:
            replicas: 1
            persistence:
              enabled: true
              size: 5Gi
              storageClass: synology-loki
              accessMode: ReadWriteOnce

          write:
            replicas: 1
            # Force single instance
            affinity: null
            podAntiAffinity: null
            persistence:
              enabled: true
              size: 20Gi
              storageClass: synology-loki
              accessMode: ReadWriteOnce

        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
          lokiCanary:
            enabled: false
          rules:
            enabled: false

        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Force=true # Added force option to ensure full refresh
