apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.27.0
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: filesystem
          persistence:
            enabled: true
            storageClassName: synology-loki
            size: 30Gi
          config:
            compactor:
              shared_store: filesystem
            storage_config:
              filesystem:
                directory: /data/loki/chunks
        serviceMonitor:
          enabled: true
        monitoring:
          selfMonitoring:
            enabled: true
            grafanaAgent:
              installOperator: false
        gateway:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
