apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.27.0
    helm:
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          auth_enabled: false
        backend:
          replicas: 1
        write:
          replicas: 1
        read:
          replicas: 1
        monitoring:
          lokiCanary:
            enabled: false
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 30Gi
            storageClassName: synology-loki
        minio:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
