apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.27.0
    helm:
      values: |
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClassName: synology-loki
            size: 30Gi
        loki:
          auth_enabled: false
          structuredConfig:
            common:
              path_prefix: /var/loki
              storage:
                filesystem:
                  chunks_directory: /var/loki/chunks
                  rules_directory: /var/loki/rules
              ring:
                kvstore:
                  store: memberlist
            schema_config:
              configs:
                - from: "2020-10-24"
                  store: boltdb-shipper
                  object_store: filesystem
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            storage_config:
              boltdb_shipper:
                active_index_directory: /var/loki/index
                cache_location: /var/loki/cache
                cache_ttl: 24h
                shared_store: filesystem
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
