apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.27.0
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2023-01-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v12
                index:
                  prefix: index_
                  period: 24h
          storage_config:
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/cache
              cache_ttl: 24h
              shared_store: filesystem
            filesystem:
              directory: /var/loki/chunks
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 1
          limits_config:
            retention_period: 168h

        singleBinary:
          replicas: 1
          nodeSelector:
            kubernetes.io/hostname: k3s-work-04
          persistence:
            enabled: true
            size: 10Gi
            storageClass: synology-loki

        monitoring:
          serviceMonitor:
            enabled: true
            namespace: monitoring
          selfMonitoring:
            enabled: true
            grafanaAgent:
              installOperator: false

        service:
          type: LoadBalancer
          port: 3100

        networkPolicy:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
