apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.27.0
    helm:
      values: |
        deploymentMode: "SingleBinary<->SimpleScalable"

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
            storageClass: synology-loki
          nodeSelector:
            kubernetes.io/hostname: k3s-work-04
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        read:
          replicas: 0
          persistence:
            enabled: false

        write:
          replicas: 0
          persistence:
            enabled: false

        backend:
          replicas: 0
          persistence:
            enabled: false

        service:
          type: LoadBalancer
          port: 3100

        monitoring:
          serviceMonitor:
            enabled: true
            namespace: monitoring
          selfMonitoring:
            enabled: true
            grafanaAgent:
              installOperator: false

        networkPolicy:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
