apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.0.0
    chart: kube-prometheus-stack
    helm:
      values: |
        crds:
          create: false

        grafana:
          persistence:
            enabled: true
            storageClassName: synology-nfs
            size: 10Gi
            subPath: "grafana"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: workload-type/monitoring
                      operator: In
                      values:
                      - "true"

        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-nfs
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 80Gi
                  volumeName: synology-nfs-pv
              subPath: "prometheus"
            retention: 30d
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: workload-type/monitoring
                      operator: In
                      values:
                      - "true"

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-nfs
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 10Gi
                  volumeName: synology-nfs-pv
              subPath: "alert-manager"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: workload-type/monitoring
                      operator: In
                      values:
                      - "true"

        prometheusOperator:
          admissionWebhooks:
            enabled: true
          tlsProxy:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: workload-type/monitoring
                    operator: In
                    values:
                    - "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipCRDs=true
