apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.2.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        grafana:
          persistence:
            enabled: true
            storageClassName: synology-nfs
            size: 10Gi
            subPath: grafana
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: workload-type/monitoring
                        operator: In
                        values:
                          - "true"
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
              traefik.ingress.kubernetes.io/router.middlewares: "default-redirect-https@kubernetescrd"
            hosts:
              - grafana.gitopsguy.com
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.gitopsguy.com

        prometheus:
          prometheusSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-nfs
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 80Gi
                  volumeName: synology-nfs-pv
            volumeMounts:
              - name: storage-volume
                mountPath: /prometheus
                subPath: prometheus
            retention: 30d
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: workload-type/monitoring
                          operator: In
                          values:
                            - "true"
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
              traefik.ingress.kubernetes.io/router.middlewares: "default-redirect-https@kubernetescrd"
            hosts:
              - prometheus.gitopsguy.com
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.gitopsguy.com

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-nfs
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 10Gi
                  volumeName: synology-nfs-pv
            volumeMounts:
              - name: storage-volume
                mountPath: /alertmanager
                subPath: alertmanager
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: workload-type/monitoring
                          operator: In
                          values:
                            - "true"

        prometheusOperator:
          admissionWebhooks:
            enabled: true
          tlsProxy:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: workload-type/monitoring
                        operator: In
                        values:
                          - "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
