apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.2.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        grafana:
          persistence:
            enabled: true
            storageClassName: synology-grafana
            accessModes:
              - ReadWriteMany
            size: 10Gi

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - k3s-work-04
                          - k3s-work-08
                          - k3s-work-12
                          - k3s-work-16

          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule

        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-prometheus
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 80Gi
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: workload-type/monitoring
                          operator: In
                          values:
                            - "true"

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: synology-alertmanager
                  accessModes: ["ReadWriteMany"]
                  resources:
                    requests:
                      storage: 10Gi

            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: workload-type/monitoring
                          operator: In
                          values:
                            - "true"

        prometheusOperator:
          admissionWebhooks:
            enabled: true
          tlsProxy:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: workload-type/monitoring
                        operator: In
                        values:
                          - "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
