---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd  # Adjust to match your ArgoCD namespace
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
            defaultClass: true
            defaultFsType: ext4
    - repoURL: "https://github.com/jsmithgh/argocd"
      targetRevision: HEAD
      path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
