apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClass: true
            defaultFsType: ext4
          defaultSettings:
            createDefaultDiskLabeledNodes: true
            defaultDataPath: /var/lib/longhorn/
            defaultReplicaCount: 3
          storageClasses:
            - name: longhorn-rwx
              defaultClass: false
              reclaimPolicy: Retain
              allowVolumeExpansion: true
              parameters:
                numberOfReplicas: "3"
                staleReplicaTimeout: "30"
                fsType: "nfs"
                dataLocality: "disabled"
    - repoURL: "https://github.com/jsmithgh/argocd"
      targetRevision: HEAD
      path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
