apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "nfs"
  dataLocality: "disabled"
  recurringJobs: ""
  diskSelector: ""
  nodeSelector: ""
allowVolumeExpansion: true
reclaimPolicy: Retain
