prometheusOperator:
  admissionWebhooks:
    enabled: true
  tlsProxy:
    enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload-type/monitoring
                operator: In
                values:
                  - "true"
